### ISSUE TITLE
Best way to connect laravel routes and react-router?

### ISSUE THREAD

**Issue by brenelz** [talyssonoc/react-laravel#14]
Loving this package... got this all working in an app.  

One question I have is how would you hook up the routing.  I see 2 options. 
1. Keep client-side routing on the client - and only use Laravel for api stuff or full page reloads
2. Pass Laravel routes to the react-router if they don't exist (404)

Thoughts?

**Comment by talyssonoc** [comment]
Huum, for now I would use the first option, the second seems wrong.

But, as I said, it's for now, I'm planning to create a `@react_router` directive soon !

**Comment by brenelz** [comment]
That sounds pretty cool... why would you write your react routes in blade though?

**Comment by talyssonoc** [comment]
Actually I wouldn't, the directive would mount and run the router, as the `@react_component` do for components, I'm still thinking about it, suggestions are welcome.

**Comment by brenelz** [comment]
I do think  connecting the routing somehow would be pretty awesome.  Just thinking myself how I would like that to work.

**Comment by talyssonoc** [comment]
Hey, @brenelz, sorry by the delay, I've been busy ! I'm thinking about building something using [laroute](https://github.com/aaronlord/laroute), what do you think ?

**Comment by a-moses** [comment]
@brenelz  good direction we need something like [isomorphic app](http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/) .

send to client all route needed for the page if javascript fallback  or client going to other page route it from  the server.

**Comment by karlonauger** [comment]
@talyssonoc I like the laroute idea.
For me, the real appeal of a client-side app is the quick response of the UI, as the app only gets page specific (often Json) data from the server, following navigation. 
Would this allow us to access important Laravel features like route specific middleware, and route bindings?

**Comment by talyssonoc** [comment]
Hi, @karlonauger, as it would just generate the URL for the route I would say yes, it would allow access to middlewares and so on. I think it would let React just make ajax requests to the given URL and, there, you can say what will be sent to the client (something like this pjax example: https://github.com/defunkt/jquery-pjax#server-side), what do you think ?

**Comment by karlonauger** [comment]
That sounds great! It would save me a ton of time trying to re-design, and duplicate client-side authentication.

**Comment by yukulelix** [comment]
Hey there, any update on this ? Cheers ;)

**Comment by salamex** [comment]
cheers

**Comment by henfreire** [comment]
Do you know how to access direct a permanent link create by react creating the route in laravel?
