### ISSUE TITLE
can use JSX  

### ISSUE THREAD

**Issue by limweb** [talyssonoc/react-laravel#20]
can use JSX  in this lib

**Comment by talyssonoc** [comment]
Yes, you can, but not directly (yet, I just had an idea that will make it possible), for now you should use it: https://github.com/joecohens/laravel-elixir-react

**Comment by TomCaserta** [comment]
Gunna watch this for updates as this is something i'd like. 

Managed to get it to work in a very hacky way. Made an exp() function that exports the module to window or "global" depending on which exists. Then edited the php react class to load in modules on the "global" name space by prepending the component name with "global.". Appears to all work but is a very patch work method.

**Comment by 18601673727** [comment]
@limweb Actually you could use Elixir's babel() function to transpile your JSX into javascript in `Laravel5.1`

**Comment by talyssonoc** [comment]
@18601673727 When I answered this question Babel hadn't landed at Elixir yet, but I agree with him @limweb, use Babel would be a better choice !

**Comment by talyssonoc** [comment]
@limweb @18601673727 I've built this to use internally, what do you think ? https://github.com/talyssonoc/php-babel-transpiler

**Comment by limweb** [comment]
thanks.
