### ISSUE TITLE
Install V8.JS with composer

### ISSUE THREAD

**Issue by bhargavjoshi** [talyssonoc/react-laravel#22]
Hi, Great library I was thinking to make a similar package, You have done a fantastic job. 

When I was thinking to develop this package, I was thinking it would be great if we can install v8.js as pear package through composer. [Example](http://stackoverflow.com/questions/21519919/composer-install-pear-package)

Can we implement this in the package?

**Comment by talyssonoc** [comment]
Hey, thanks, I'm glad you like it !

Well, I guess v8.js is not available at PEAR, just at PECL (and its support is not that great there too, sadly).

Other thing is that v8.js is not a dependency of `react-laravel` itself, but of `react-php-v8js`, maybe if it was possible this should be there.
