### ISSUE TITLE
Update reactjs/react-php-v8js on Packagist

### ISSUE THREAD

**Issue by TomCaserta** [talyssonoc/react-laravel#26]
Hi noticed you was maintainer of the packagist package. 

It doesn't seem to be updated to reflect changes with the global/window object and as such my components written in JSX transpiled with browserify are not working correctly since its not got a global scope for the components to be placed into. 

Without it this is all I get when I render my components:

```
 V8Js::executeString():23460: ReferenceError: <COMPONENT NAME> is not defined
```

Are you able to update it to reflect the changes made in: https://github.com/reactjs/react-php-v8js/pull/6/files

Thanks,

**Comment by talyssonoc** [comment]
Hi, @TomCaserta, just update it !
