### ISSUE TITLE
@react_component directive not working?

### ISSUE THREAD

**Issue by nrcook** [talyssonoc/react-laravel#28]
Laravel 5.1, React-laravel 0.9.1

Tried on a couple different Laravel apps, both 5.0.\* and 5.1.  Neither one seemed to render the @react_component directive.  Is there a missing step for getting this up and running that's not in the Readme?

Thanks!

**Comment by lgt** [comment]
+1

**Comment by talyssonoc** [comment]
Well, it should be working, sadly you're not the first to say this, I don't know yet what's happening. Can you try to use this example project (I should link to it at readme) https://github.com/talyssonoc/react-laravel-example ?

**Comment by nrcook** [comment]
Just tried, no that example project is not working for me either.  Running this on Homestead, though not sure why that would make a difference.

**Comment by nrcook** [comment]
Just looked through some of the source, looks like you are using Facades now?  I changed a line in the sample project to `{!!React::render('Message', [ 'name' => 'Hue' ])!!}` and it did work.

**Comment by talyssonoc** [comment]
@nrcook actually react-laravel always used facades, what `@react_component` directive did was call this facade, good to know that the facade work, the error must be in the registration of the directive...

**Comment by a-moses** [comment]
maybe we need to compile specific version of V8 lib  not the last  one and not to   older one   like 1.3

what is the working version stable  of v8  lib working on ubuntu ?

**Comment by TomCaserta** [comment]
Yeah right now you cannot have a deferred service provider and a blade directive as it doesnt know to load the service provider associated with the directive. Hopefully in future laravel versions it would be possible for that to work. For now, I personally have just set the deferred property to false to get it to work.

**Comment by talyssonoc** [comment]
Well, I didn't know that ! Gonna fix it later today (a PR would be good, too). Thanks, @TomCaserta !

**Comment by talyssonoc** [comment]
@TomCaserta @nrcook @lgt can you try this instructions here and say me if it does work? https://github.com/talyssonoc/react-laravel/issues/41#issuecomment-133704745
