### ISSUE TITLE
Are components cached somewhere?

### ISSUE THREAD

**Issue by ghost** [talyssonoc/react-laravel#29]
Tried running the react larval example, the "Message" directive worked fine. 
However changes to the public/js/components.js file does not seem to affect the rendering of components one bit. I deleted the file and it still works the same way.

**Comment by talyssonoc** [comment]
It caches only in production environment: https://github.com/talyssonoc/react-laravel/blob/master/lib/ReactServiceProvider.php#L49

**Comment by ghost** [comment]
@talyssonoc Worked perfectly, thanks!
