### ISSUE TITLE
could someone please set minimum-stability to stable?

### ISSUE THREAD

**Issue by 18601673727** [talyssonoc/react-laravel#31]
I must to say this package is a great work, but I need to use this package in production env, so `"minimum-stability": "dev"` as mentioned in doc is too dangerous to me, or is there a way to set minimum-stability to dev for specific package?

**Comment by talyssonoc** [comment]
@18601673727 You can use `prefer-stable` option :smile: https://getcomposer.org/doc/04-schema.md#prefer-stable
