### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cklouman** [talyssonoc/react-laravel#37]
Hey @talyssonoc, this package looks awesome and I'm considering it for an upcoming project. There is however no license - will you consider including one? I will not be able to use it without an explicit open-source license unfortunately.

**Comment by talyssonoc** [comment]
Actually the license is at the `composer.json` file, but I got to admit I forgor to put it on the repository, gonna do it soon ! For now, you can consider the `composer.json` that say it is MIT license (and it won't change). :D

**Comment by cklouman** [comment]
cool thx! - thought I must have missed something :)
