### ISSUE TITLE
IE9 Invalid calling object

### ISSUE THREAD

**Issue by matthewfowles** [talyssonoc/react-laravel#40]
Hi 

I am having issues with IE9. 

![Uploading image.png
<img width="704" alt="screenshot 2015-08-17 11 55 30" src="https://cloud.githubusercontent.com/assets/622010/9303783/2e94c662-44d9-11e5-9248-e4a17a4adfa8.png">
…]()

I just wondered if anyone had seen this behaviour before and may know a work around.

Thanks

**Comment by talyssonoc** [comment]
Well, that's weird, since this is [line 31](https://github.com/talyssonoc/react-laravel/blob/master/assets/react_ujs.js#L31). What React Laravel version are you using?

**Comment by matthewfowles** [comment]
```
"talyssonoc/react-laravel": "0.9.1",
```

It's all a bit weird. The only thing I can think of is it might be trying to re-create global vars that already exist? As the components are on the window.

I also just get nothing in IE8. Not sure if this is related.

**Comment by talyssonoc** [comment]
@matthewfowles Can you try this instructions here and say me if it does work? https://github.com/talyssonoc/react-laravel/issues/41#issuecomment-133704745

**Comment by talyssonoc** [comment]
@matthewfowles huuum, maybe it's a bug between React and IE9? If you click on `react_ujs.js, line 31, character 9` where does it take you to?

**Comment by matthewfowles** [comment]
It takes me too the right line. 

I have actually solved it. Not sure exactly what it was but I was trying to fix IE8 as well which had separate issues. Once I included all suggested polyfills and added some addEventListener polyfills it started working. 

I'm not sure quite what the issue was but thanks for the help :+1:

**Comment by talyssonoc** [comment]
@matthewfowles Well, it must be because of this, glad it works for you now!
