### ISSUE TITLE
Configuration caching is unnecessary in Laravel 5.x

### ISSUE THREAD

**Issue by dwightwatson** [talyssonoc/react-laravel#42]
Laravel 5.1 supports config caching out of the box (with the `config:cache` command) which would generally be used after a deployment to cache any new configuration values. This makes the manual caching performed by the service provider unnecessary, and even more painful than it would be otherwise if you wanted to update the configuration in a release - you'd have to manually clear the cache.

Happy to submit a PR for this and update the docs if you're interested.

**Comment by talyssonoc** [comment]
Sorry by the delay, @dwightwatson. A PR for this would be awesome, feel free to do it! :)

**Comment by willvincent** [comment]
See PR #74
