### ISSUE TITLE
The requested PHP extension v8js is missing from your system

### ISSUE THREAD

**Issue by dotMastaz** [talyssonoc/react-laravel#43]
Hello,

I install v8js in homestead... Phpinfo() return v8js enabled...
But when i try : composer update, i have this error :+1: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - reactjs/react-php-v8js dev-master requires ext-v8js >=0.1.3 -> the requested PHP extension v8js is missing from your system.
    - talyssonoc/react-laravel v0.9.1 requires reactjs/react-php-v8js dev-master -> satisfiable by reactjs/react-php-v8js[dev-master].
    - Installation request for talyssonoc/react-laravel 0.9.1 -> satisfiable by talyssonoc/react-laravel[v0.9.1].

**Comment by dotMastaz** [comment]
Ok, i run it into the server (homestead) : vagrant ssh, compose rupdate
And it's ok !!

**Comment by gronel** [comment]
I got same error were I can download v8js.dll please help.. thanks
