### ISSUE TITLE
v8js compil error in CentOS

### ISSUE THREAD

**Issue by dotMastaz** [talyssonoc/react-laravel#47]
Hello,

I try to compil v8js to CentOS but i have an error :

checking for V8 version... NONE
configure: error: could not determine libv8 version

Any idea ?
Thank you !!

**Comment by talyssonoc** [comment]
Did you make sure you have done this step? https://github.com/phpv8/v8js/blob/master/README.Linux.md#compile-latest-v8

If so, check the paths used in the tutorial, maybe some of them is different on CentOS!

Hope it helps :smile:
