### ISSUE TITLE
Update react to v0.14

### ISSUE THREAD

**Issue by 18601673727** [talyssonoc/react-laravel#49]
please see [this](https://www.npmjs.com/package/react-bootstrap#react-v0-13-support)

**Comment by talyssonoc** [comment]
Waiting for this to be merged to update to v0.14: https://github.com/reactjs/react-php-v8js/pull/19

**Comment by 18601673727** [comment]
@talyssonoc  Cool :+1:

**Comment by htchaan** [comment]
[reactjs/react-php-v8js#19](https://github.com/reactjs/react-php-v8js/pull/19) has been merged, please help.

New install won't work at the moment: `V8Js::compileString():1: TypeError: Cannot read property 'renderToString' of undefined`.

**Comment by htchaan** [comment]
Prerender works again with the `react-bundle.js` from [example of react-php-v8js](https://github.com/reactjs/react-php-v8js/tree/master/example).
