### ISSUE TITLE
talyssonoc/react-laravel v0.10.2 requires reactjs/react-php-v8js dev-maste r -> no matching package found.

### ISSUE THREAD

**Issue by Danjavia** [talyssonoc/react-laravel#50]
Can you restore value in package.json from dev-master to master?

**Comment by talyssonoc** [comment]
@Danjavia, can you show me the full error message here?

**Comment by Danjavia** [comment]
Yes.

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for talyssonoc/react-laravel 0.10.2 -> satisfiable by
 talyssonoc/react-laravel[v0.10.2].
    - talyssonoc/react-laravel v0.10.2 requires reactjs/react-php-v8js dev-maste
r -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

**Comment by talyssonoc** [comment]
Did you remembered to set `"minimum-stability": "dev"` on your `composer.json` like it's said [here](https://github.com/talyssonoc/react-laravel#composer)?

**Comment by Danjavia** [comment]
yes I do but appear another error also

Check it:

  Problem 1
    - The requested package minimum-stability could not be found in any version,
 there may be a typo in the package name.
  Problem 2
    - Installation request for talyssonoc/react-laravel 0.10.2 -> satisfiable by
 talyssonoc/react-laravel[v0.10.2].
    - talyssonoc/react-laravel v0.10.2 requires reactjs/react-php-v8js dev-maste
r -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

**Comment by talyssonoc** [comment]
Can tou show me your `composer.json`, @Danjavia?

**Comment by Danjavia** [comment]
```
{
"name": "laravel/laravel",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"type": "project",
"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.1.*",
    "laravel/socialite": "^2.0"
},
"require-dev": {
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~4.0",
    "phpspec/phpspec": "~2.1",
    "ignited/laravel-omnipay": "2.*",
    "omnipay/paypal": "~2.0",
    "minimum-stability": "dev",
    "talyssonoc/react-laravel": "0.10.2"
},
"autoload": {
    "classmap": [
        "database"
    ],
    "psr-4": {
        "Infinity\\": "app/"
    },
    "files": [ "app/Http/helpers.php" ]
},
"autoload-dev": {
    "classmap": [
        "tests/TestCase.php"
    ]
},
"scripts": {
    "post-install-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
    ],
    "pre-update-cmd": [
        "php artisan clear-compiled"
    ],
    "post-update-cmd": [
        "php artisan optimize"
    ],
    "post-root-package-install": [
        "php -r \"copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
        "php artisan key:generate"
    ]
},
"config": {
    "preferred-install": "dist"
}
```

}

**Comment by talyssonoc** [comment]
oh, `"minimum-stability": "dev"` is not a dependency, it must be in a separated key, like right before "config", something like that:

``` json
   ...
   "minimum-stability": "dev",
   "config": {
      "preferred-install": "dist"
   }
   ...
```

**Comment by Danjavia** [comment]
Ok perfect i will to try it thanks @talyssonoc

**Comment by talyssonoc** [comment]
Could you close the issue if it works, @Danjavia? :smile:

**Comment by Danjavia** [comment]
thanks again  I will to write to you when I Do ;)

**Comment by talyssonoc** [comment]
@Danjavia did it worked?

**Comment by Danjavia** [comment]
Sorry I cannot yet, pls sorry I will to do in a few days :)

**Comment by talyssonoc** [comment]
@Danjavia?

**Comment by Danjavia** [comment]
Not really, sorry my boss has change the app requirements! Thx!!! :)
