### ISSUE TITLE
Have you guys ever succeed using this with React addons?

### ISSUE THREAD

**Issue by 18601673727** [talyssonoc/react-laravel#53]
I did this:

``` jsx
...
React.createClass({
  mixins: [LinkedStateMixin],

  getInitialState() {
...
```

and

```
V8Js::compileString():38264: ReferenceError: LinkedStateMixin is not defined
```

:disappointed_relieved:

**Comment by 18601673727** [comment]
and I'm pretty sure that I'm using this file `react-with-addons.js` to compile on both side.

**Comment by talyssonoc** [comment]
Try to use: `mixins: [React.addons.LinkedStateMixin]`

**Comment by talyssonoc** [comment]
@18601673727?

**Comment by 18601673727** [comment]
@talyssonoc Yeah, I think this could been closed, thanks for the help!
