### ISSUE TITLE
Construct ReactJS only when needed. 

### ISSUE THREAD

**Issue by TomCaserta** [talyssonoc/react-laravel#60]
I have been profiling and building a faster version, as I have added custom methods which are only relevant to my codebase I have not had the time to make a pull request to this library. This issue is just a reminder for me to make a PR at some point. In any case:

Currently regardless of if the page has prerendering enabled the server will still construct the ReactJS class which in turn executes the reactjs source. This can slow down websites that do not use ReactJS server side rendering as it is needlessly executing the source code (Large React sources can cause upwards of 200ms execution time).

**Comment by talyssonoc** [comment]
@TomCaserta indeed! I'll be glad to see a PR to fix that and conditionally load the source code only if prerender is enabled!
