### ISSUE TITLE
v8js on Laravel Homestead with php7

### ISSUE THREAD

**Issue by BeggarsMattM** [talyssonoc/react-laravel#66]
I just can't get the above combination to work no matter what I try.

pecl install v8js-0.2.0 fails because "libv8 must be version 3.24.6 or greater"

pecl install v8js-0.1.3 fails because "ext/standard/php_smart_str.h: No such file or directory"

All dependencies are installed as far as I can see. Is there any help for this at the moment?

**Comment by TomCaserta** [comment]
Have you tried installing a newer version of libv8 from source?

**Comment by BeggarsMattM** [comment]
Ah yes, sorry, it took a couple of hours to fumble my way through the documentation but you're completely correct, that does work. If I have to do this again every time I restart Vagrant I'm not sure it's a realistic proposition though! And for all my efforts I am rewarded with "V8Js::compileString():1: ReferenceError: Message is not defined"... but I'm sure that's a completely different problem.

Thanks for your help.

**Comment by TomCaserta** [comment]
Hah yeah its an absolute pain, especially when you recreate your vagrant vm (shouldnt be required every time you restart though). We do need a better way but it does mean some form of provision script that'd take an hour to build libv8 (at least on my machine!).

Glad its at least in a state of semi working! 

That reminds me, we do need better error handling too.

**Comment by BeggarsMattM** [comment]
I wonder if you could help me work out what's gone wrong with my install, given that if I try to create a component with 'prerender' => true I get the above error ('V8Js::compileString():1: ReferenceError: Message is not defined'). 'prerender' => false works fine!

**Comment by TomCaserta** [comment]
Hmf, it sounds like the javascript is not being loaded serverside. Can you double check your paths in your configuration to the javascript file and make sure the Messages class exists in that file.

**Comment by BeggarsMattM** [comment]
All the paths in config/react.php look correct to me... very confusing!

**Comment by BeggarsMattM** [comment]
Actually I can mess around with the contents of config/react.php quite a lot and it doesn't make any difference that I can see. Is there any way that could not be being found?

**Comment by BeggarsMattM** [comment]
Okay, never mind, some liberal clearing of everything I could think of with artisan seems to have resolved the issue. We have liftoff!
