### ISSUE TITLE
Multiple react apps within single laravel instance

### ISSUE THREAD

**Issue by kenpeter** [talyssonoc/react-laravel#67]
Right now, all react components goes into 'components' => public_path('js/components.js'). Is it possible to have something like

In config/react.php

```
'components' => [
public_path('js/app_1_components.js'),
public_path('js/app_2_components.js'),
public_path('js/app_3_components.js'),
]
```

**Comment by TomCaserta** [comment]
Currently it is not possible, I guess you could concatenate the files into one using laravel-elixir/gulp. In any case this sounds like a good feature to add. I'll make a pull request sometime soon.

**Comment by willvincent** [comment]
See PR #75
