### ISSUE TITLE
'prerender' => false is not working

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [talyssonoc/react-laravel#68]
Hello.
I'm trying to render on the client side by setting `'prerender' => false` but it does nothing. What do I do wrong?

**Comment by KonstantinKolodnitsky** [comment]
Here is an example of my component

```
var Cards = React.createClass({
    displayName: "Cards",

    getInitialState: function() {
        return {data: JSON.stringify([])};
    },

    loadDataFromServer: function() {
        $.ajax({
            url: this.props.api_url,
            dataType: 'json',
            cache: false,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    },

    componentDidMount: function() {
        this.loadDataFromServer();
       setInterval(this.loadDataFromServer, this.props.pollInterval);
    },

render: function () {
    var streamCards = JSON.parse(this.state.data).map(function (card) {
       React.createElement(Card, {data: card, key: card.id})
    });
    return (
        React.createElement("div", {className: this.className},
            streamCards
        )
    );
}

});
```

Calling it

```
@react_component('Cards', $opts, ['prerender' => false])
```

**Comment by KonstantinKolodnitsky** [comment]
If I set it to`true` it is working but `componentDidMount` is not fired. But if I set it to `false` nothing happens at all.

**Comment by TomCaserta** [comment]
Are there any errors in the console? What  version are you using and what browser?

To me this sounds like the javascript responsible for loading React and rendering is getting called after the document has already downloaded. I did put in a fix that should have fixed this by checking if the document was already loaded (and then just render it as normal instead of setting an event handler) but there might be some form of document state I may have missed.

**Comment by KonstantinKolodnitsky** [comment]
Hi Tom
I use v0.11. Chrome.
Yes, there are some error, but they were before I added componentDidMount. 

react.js:18794 Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.

react.js:18794 Warning: Unknown DOM property enctype. Did you mean encType?

**Comment by TomCaserta** [comment]
Hmm so thats with prerender on correct? What about with it off?

If there is no errors and nothing react like is appearing in the container then I suspect react_ujs.js is not doing its job... Are you able to place a couple console.log statements in the reactujs file to see if its actually getting to the handleEvents function and what route it is taking (or of course just set breakpoints). Or alternatively do you have any form of live example (I assume not but worth asking).

**Comment by KonstantinKolodnitsky** [comment]
Nevermind. Errors are from another component. I've disabled it and errors are gone.

There is no error with this component either prerender enabled or disabled. Also I'd say that with prerender disabled the component is not loaded at all. I've put console.error('componentDidMount'); into the getInitialState and there is no error in the console (if prerender set to false)

**Comment by TomCaserta** [comment]
Yeah, just trying to figure out why it is not loading the component - especially if another component is getting loaded correctly on the same page. Quite odd, if you could just try putting the console.error statement in the react_ujs.js file then we can see if its even attempting to render the component.

**Comment by KonstantinKolodnitsky** [comment]
Yes, it does show my error message.
I've put console.error right after ReactLaravelUJS.handleEvents();

**Comment by KonstantinKolodnitsky** [comment]
Also I've checked if condition in handleEvents and the statement

```
if (document.readyState == "complete" || document.readyState == "loaded" || document.readyState == "interactive") {
```

 is false

**Comment by KonstantinKolodnitsky** [comment]
document.readyState is 'loading'

**Comment by TomCaserta** [comment]
In that case it should add the event to load once the document has finished loading. Does mountComponents() get called? Whilst we are at it could you try logging with: console.log(reactClass, props) just before line 35 and see if that shows anything?

**Comment by KonstantinKolodnitsky** [comment]
`mountComponents` is called (added console at the top) but `elements` is empty so `for` is doing nothing

**Comment by TomCaserta** [comment]
Hmf, must be something to do with the HTML that we are putting into the page. Can you paste the html that the `@react_component` line generates? Not sure what could be causing that though. Not that this should matter but does it look like there is any tag mismatches that could possibly be causing it not to find the element. 

Just trying to make sense of it really, are you using jquery on the page? If so, what version?

**Comment by KonstantinKolodnitsky** [comment]
Wow. I've found a problem. I had a commented blade tags and when they was compiled one was compiled incorrectly so I had {{-- in the html.

As usually most of the problems are made by developers :)
Now it's working (I hope). componentDidMount is called so I'm sure the component is loaded.

Thank for your help!

**Comment by TomCaserta** [comment]
Hah small little errors like that always creep in. No problem, glad its working now!
