### ISSUE TITLE
Configuring

### ISSUE THREAD

**Issue by aprilmintacpineda** [talyssonoc/react-laravel#76]
Hi I am new to laravel and to reactJS. I am using gulp to mix all my scripts into one file. What am I suppose to put in these? how am I suppose to configure react-laravel? I have a fresh laravel installation with `react-laravel`, react-and-friends: `react.js, react-dom.js, react-router.js` installed via npm.

```
  return [
    'source' => 'path_for_react.js',
    'dom-source' => 'path_for_react-dom.js',
    'dom-server-source' => 'path_for_react-dom-server.js',
    'components' => [ 'path_for_file_containing_your_components.js' ]
  ];
```

**Comment by talyssonoc** [comment]
@four-eyes-04-04 you should put the path for the libs and your components there. Something like:

``` php
  return [
    'source' => base_path('node_modules/react/dist/react.js'),
    'dom-source' => base_path('node_modules/react-dom/dist/react-dom.js'),
    'dom-server-source' => base_path('node_modules/react-dom/dist/react-dom-server.js'),
    'components' => [ public_path('js/<the path for your the file with your components compiled>') ]
  ];
```

**Comment by aprilmintacpineda** [comment]
@talyssonoc 

Okay that makes sense, so I don't need to mess with my scripts right? like I think the php-react requires that I do something like

```
echo '<script>' . $rjs->getJS("#here") . '</script>';
```

and also

```
echo '<div id="here">' . $rjs->getMarkup() . '</div>';
```

I saw this on [react-phpv8js](https://github.com/reactjs/react-php-v8js) and I am really confused with that.

**Comment by talyssonoc** [comment]
@four-eyes-04-04 nop, we do that for you! https://github.com/talyssonoc/react-laravel/blob/master/lib/React.php#L54 😄

**Comment by aprilmintacpineda** [comment]
wow thanks a lot! saves me the awfulness! You're a life saver! :-)
